### ISSUE TITLE
Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.

### ISSUE THREAD

**Issue by michalkrzych** [cake-contrib/Cake.Sonar#113]
Hi. Ive added the two below lines to my addins.cake 
```
#tool "nuget:?package=MSBuild.SonarQube.Runner.Tool&version=4.8.0"
#addin "nuget:?package=Cake.Sonar&version=1.1.29"
```
I also added and configured the Tasks
```
Task("SonarBegin")
  .Does(() => {
     SonarBegin(new SonarBeginSettings{
        Key = "cakeSonar",
        Url = "localhost:9876",
        Login = "admin",
        Password = "admin",
        Verbose = true,
        ArgumentCustomization = args => args
            .Append("/d:sonar.login=\"\token"")
     });
  });

  Task("SonarEnd")
  .Does(() => {
     SonarEnd(new SonarEndSettings{
        Login = "admin",
        Password = "admin"
     });
  });
```
however, when trying to run the cake build Im getting an error and I didn't find much information on what I could possibly be missing:
```
========================================
SonarBegin
========================================
An error occurred when executing task 'SonarBegin'.

----------------------------------------
Teardown
----------------------------------------
Error: One or more errors occurred. (Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.)
        Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.
```
I found this issue which seemed related at first https://github.com/cake-build/cake/issues/677 when I ran with diagnostic this is the full error message:
```
Executing custom task setup action (SonarBegin)...

========================================
SonarBegin
========================================
Executing task: SonarBegin
Resolving assembly Cake.Common, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
Resolved Cake.Common by assembly Cake.Common, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
An error occurred when executing task 'SonarBegin'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Error: System.AggregateException: One or more errors occurred. (Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.)
 ---> System.MissingMethodException: Method not found: 'Boolean Cake.Core.IO.FilePath.op_Equality(Cake.Core.IO.FilePath, Cake.Core.IO.FilePath)'.
   at Cake.Sonar.SonarRunner.Run(SonarSettings settings)
   at Cake.Sonar.SonarCakeAliases.SonarBegin(ICakeContext context, SonarBeginSettings settings)
   at Submission#0.SonarBegin(SonarBeginSettings settings)
   at Submission#0.<<Initialize>>b__0_121()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass29_0.<Does>b__0(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 26
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 119
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 72
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 278
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 301
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 311
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 226
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 189
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target) in C:\projects\cake\src\Cake.Cli\Hosts\BuildScriptHost.cs:line 73
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 105
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Infrastructure.Scripting.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Infrastructure\Scripting\RoslynScriptSession.cs:line 142
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 172
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 99
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 72
```
Not sure if that's much help but we're using `cake.tool` version `1.1.0` 

Any ideas/pointers are much appreciated.

**Comment by HofmeisterAn** [comment]
If I'm not wrong, Cake.Sonar `1.1.29` requires Cake `2.0.0`. Either, you downgrade your Cake.Sonar version or upgrade (that's what I recommend) to the latest Cake version.

If your pipeline supports .NET (Core), I recommand the latest Sonar Scanner too: `dotnet-sonarscanner` . In summary:

```csharp
#tool nuget:?package=dotnet-sonarscanner&version=5.5.3
#addin nuget:?package=Cake.Sonar&version=1.1.30

new SonarBeginSettings
{
    Key = "cakeSonar",
    Url = "localhost:9876",
    Login = "admin",
    Password = "admin",
    Verbose = true,
    UseCoreClr = true, // This is important to use the provided dotnet-sonarscanner
    ArgumentCustomization = args => args
        .Append("/d:sonar.login=\"\token"")
}
```

**Comment by michalkrzych** [comment]
Thank you @HofmeisterAn. Just a typo on my end with the token but props for your great eye for details :) Need to speak to my team - will get back to you as soon as I can.

**Comment by michalkrzych** [comment]
Awesome. Managed to upgrade Cake.Tools to 2.0.0 and after getting through a few initial errors managed to kick off the build. We have a mix of projects ranging between .NET 4.8 to .NET 5. Would you kindly confirm my understanding is correct that in our scenario we should be using this Scanner: `MSBuild.SonarQube.Runner.Tool&version=4.8.0`?

**Comment by HofmeisterAn** [comment]
> Would you kindly confirm my understanding is correct that in our scenario we should be using this Scanner: `MSBuild.SonarQube.Runner.Tool&version=4.8.0`?

No, not that I'm aware of. As far as I know, it doesn't matter. I use the upper suggestion in a project that targets `4.7.2`. You just need to execute the scanner somehow.

**Comment by michalkrzych** [comment]
I'm happy to close this now - Thank you @HofmeisterAn.
